### ISSUE TITLE
Socket not properly closed in Win7

### ISSUE THREAD

**Issue by sander76** [Lawouach/WebSocket-for-Python#69]
Working with python3.2, a closed socket is not properly removed from the 'pool' (?) of sockets to send a message through.

When the browser is closing its connection the server receives it, processes it (cleans all up, making the WebSocket members all None types), but somehow it stays there. Resulting in a persisting attribute error :

'NoneType' object has no attribute 'text_message'
